language: r
sudo: required

# r_build_args: "--no-build-vignettes --no-manual"
# r_check_args: "--no-build-vignettes --no-manual --as-cran"

warnings_are_errors: false

before_install:
  - tlmgr install mathdesign
  - tlmgr install bera
