language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"
warnings_are_errors: false
addons:
  apt:
    packages:
      - texlive-fonts-extra
      - texlive-latex-base
      - texlive-base
